services:
  backend:
    image: backend:latest
    container_name: backend
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config.docker.toml:/config.toml